import gymnasium as gym
from gymnasium import spaces
import numpy as np
import pandas as pd
import logging
import os
from frozen_feature_engine import FeatureEngine

class RiskPPOEnv(gym.Env):
    """
    Specialized environment for PPO-based risk model training.
    
    Optimizes SL, TP, and Size based on market conditions (40 features).
    Only trains on signals generated by the Alpha model (Qual > 0.30, Meta > 0.78).
    Uses PEEK & LABEL (simulated future outcome) to provide immediate rewards.
    """
    metadata = {'render_modes': ['human']}

    def __init__(self, data_dir='data', is_training=True, alpha_model_path=None):
        super(RiskPPOEnv, self).__init__()
        
        self.data_dir = data_dir
        self.is_training = is_training
        self.assets = ['EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'XAUUSD']
        
        # Load and Preprocess Data
        self.feature_engine = FeatureEngine()
        self.data = self._load_data()
        self.raw_data, self.processed_data = self.feature_engine.preprocess_data(self.data)
        
        # Cache for performance
        self._cache_data_arrays()
        
        # Load Alpha Model for Signal Filtering
        from Alpha.src.model import AlphaSLModel
        import torch
        self.alpha_model = AlphaSLModel(input_dim=40)
        if alpha_model_path is None:
            alpha_model_path = os.path.join(os.path.dirname(__file__), "../../Alpha/models/alpha_model.pth")
        
        if os.path.exists(alpha_model_path):
            self.alpha_model.load_state_dict(torch.load(alpha_model_path, map_location="cpu"))
            logging.info(f"Loaded Alpha model from {alpha_model_path}")
        else:
            logging.warning(f"Alpha model not found at {alpha_model_path}. Training will use random signals!")
        self.alpha_model.eval()
        self.device = torch.device("cpu")
        
        # Thresholds
        self.QUAL_THRESHOLD = 0.30
        self.META_THRESHOLD = 0.78
        
        # Observation Space: 40 features
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(40,), dtype=np.float32)
        
        # Action Space: (SL Multiplier, TP Multiplier, Position Size)
        # All in range [-1, 1] for SB3 compatibility
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(3,), dtype=np.float32)
        
        # State
        self.current_step = 0
        self.max_steps = len(self.processed_data) - 1001 # Leave room for PEEK
        self.current_asset_idx = 0
        
        # Configuration
        self.LEVERAGE = 100
        self.EQUITY = 10000.0

    def _load_data(self):
        data = {}
        for asset in self.assets:
            file_path = f"{self.data_dir}/{asset}_5m.parquet"
            if not os.path.exists(file_path):
                # Fallback to current directory data folder if not found
                file_path = os.path.join(os.path.dirname(__file__), "..", "data", f"{asset}_5m.parquet")
            
            try:
                df = pd.read_parquet(file_path)
            except Exception as e:
                logging.error(f"Failed to load {asset}: {e}")
                # Create dummy if everything fails
                dates = pd.date_range(start='2024-01-01', periods=2000, freq='5min')
                df = pd.DataFrame(index=dates)
                df[f"{asset}_open"] = 1.0; df[f"{asset}_high"] = 1.01; df[f"{asset}_low"] = 0.99; df[f"{asset}_close"] = 1.0; df[f"{asset}_volume"] = 100; df[f"{asset}_atr_14"] = 0.001
                
            data[asset] = df
        return data

    def _cache_data_arrays(self):
        self.close_arrays = {a: self.raw_data[f"{a}_close"].values.astype(np.float32) for a in self.assets}
        self.low_arrays = {a: self.raw_data[f"{a}_low"].values.astype(np.float32) for a in self.assets}
        self.high_arrays = {a: self.raw_data[f"{a}_high"].values.astype(np.float32) for a in self.assets}
        self.atr_arrays = {a: self.raw_data[f"{a}_atr_14"].values.astype(np.float32) for a in self.assets}

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        
        # Find next valid signal from Alpha model
        self.current_step = np.random.randint(500, self.max_steps - 500)
        self._find_next_signal()
        
        obs = self._get_observation()
        return obs, {}

    def _find_next_signal(self):
        """Searches for the next valid signal where Alpha model thresholds are met."""
        import torch
        max_search = 5000
        found = False
        
        while not found and max_search > 0:
            self.current_asset_idx = np.random.randint(0, len(self.assets))
            asset = self.assets[self.current_asset_idx]
            obs = self._get_observation()
            
            with torch.no_grad():
                obs_t = torch.from_numpy(obs).unsqueeze(0).to(self.device)
                dir_logits, quality, meta_logits = self.alpha_model(obs_t)
                
                direction = torch.argmax(dir_logits, dim=1).item() - 1 # -1, 0, 1
                qual_val = torch.sigmoid(quality).item()
                meta_val = torch.sigmoid(meta_logits).item()
                
            if direction != 0 and qual_val >= self.QUAL_THRESHOLD and meta_val >= self.META_THRESHOLD:
                self.current_direction = direction
                found = True
            else:
                self.current_step += 1
                if self.current_step >= self.max_steps:
                    self.current_step = 500
                max_search -= 1

    def _get_observation(self):
        asset = self.assets[self.current_asset_idx]
        current_row = self.processed_data.iloc[self.current_step]
        return self.feature_engine.get_observation(current_row, asset=asset)

    def step(self, action):
        # 1. Parse Actions
        sl_mult = np.clip((action[0] + 1) / 2 * 3.5 + 0.5, 0.5, 4.0) # 0.5 to 4.0
        tp_mult = np.clip((action[1] + 1) / 2 * 7.0 + 1.0, 1.0, 8.0) # 1.0 to 8.0
        size_pct = np.clip((action[2] + 1) / 2 * 0.49 + 0.01, 0.01, 0.5) # 1% to 50%
        
        # 2. Simulate Outcome (PEEK & LABEL)
        # Use current equity for reward calculation
        reward = self._simulate_outcome(sl_mult, tp_mult, size_pct, self.current_direction)
        
        # 3. Advance to next signal
        self.current_step += 1
        if self.current_step >= self.max_steps:
             self.current_step = 500
             
        self._find_next_signal()
        
        obs = self._get_observation()
        
        terminated = False
        truncated = False
        
        return obs, reward, terminated, truncated, {}

    def _simulate_outcome(self, sl_mult, tp_mult, size_pct, direction):
        asset = self.assets[self.current_asset_idx]
        price = self.close_arrays[asset][self.current_step]
        atr = self.atr_arrays[asset][self.current_step]
        
        if atr <= 0: atr = price * 0.001
        
        sl_dist = sl_mult * atr
        tp_dist = tp_mult * atr
        sl_price = price - (direction * sl_dist)
        tp_price = price + (direction * tp_dist)
        
        # Look ahead
        start_idx = self.current_step + 1
        end_idx = min(start_idx + 1000, len(self.raw_data))
        
        lows = self.low_arrays[asset][start_idx:end_idx]
        highs = self.high_arrays[asset][start_idx:end_idx]
        
        if direction == 1:
            sl_hit_mask = lows <= sl_price
            tp_hit_mask = highs >= tp_price
        else:
            sl_hit_mask = highs >= sl_price
            tp_hit_mask = lows <= tp_price
        
        sl_hit = sl_hit_mask.any()
        tp_hit = tp_hit_mask.any()
        
        if sl_hit and tp_hit:
            first_sl = np.argmax(sl_hit_mask)
            first_tp = np.argmax(tp_hit_mask)
            exit_price = sl_price if first_sl <= first_tp else tp_price
        elif sl_hit:
            exit_price = sl_price
        elif tp_hit:
            exit_price = tp_price
        else:
            exit_price = self.close_arrays[asset][end_idx - 1]
            
        # Calculate P&L using CURRENT EQUITY (EQUITY change)
        # Reward is % change of current equity
        price_change_pct = (exit_price - price) / price * direction
        
        # Reward calculation: P&L / Current Equity * 10
        # If EQUITY changes, this reflects the impact on current balance
        pos_size_notional = size_pct * self.EQUITY
        pnl = price_change_pct * (pos_size_notional * self.LEVERAGE)
        
        reward = (pnl / self.EQUITY) * 10.0
        
        # Update simulation equity (optional for training signal, but realistic)
        self.EQUITY += pnl
        if self.EQUITY <= 0: self.EQUITY = 100.0 # Reset if busted in simulation
        
        # Penalize bad R:R
        if tp_mult < sl_mult:
            reward -= 0.1
            
        return float(reward)
